# Generated by Django 5.2.13 on 2026-04-26 18:15

import django.db.models.deletion
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Player Name')),
                ('mode', models.CharField(choices=[('past', 'Past Simple'), ('pp', 'Past Participle'), ('both', 'Both')], default='both', max_length=10)),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='Correct Answers')),
                ('wrong', models.PositiveIntegerField(default=0, verbose_name='Wrong Answers')),
                ('score_pct', models.PositiveIntegerField(default=0, verbose_name='Score (%)')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Played At')),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='IrregularVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=100, unique=True, verbose_name='Base Form')),
                ('past', models.CharField(max_length=100, verbose_name='Past Simple')),
                ('pp', models.CharField(max_length=100, verbose_name='Past Participle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Irregular Verb',
                'verbose_name_plural': 'Irregular Verbs',
                'ordering': ['base'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_index', models.PositiveIntegerField(verbose_name='Verb Number')),
                ('verb_base', models.CharField(max_length=100, verbose_name='Verb (base form)')),
                ('image', models.ImageField(upload_to=game.models.snapshot_upload_path, verbose_name='Snapshot')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Taken At')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='game.gamesession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Player Snapshot',
                'verbose_name_plural': 'Player Snapshots',
                'ordering': ['verb_index'],
            },
        ),
    ]
