# Generated by Django 5.2.15 on 2026-07-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('coin_reward', models.PositiveIntegerField(default=0)),
                ('condition_type', models.CharField(choices=[('games_played', 'Total Games Played'), ('streak', 'Streak Days Reached'), ('total_xp', 'Total XP Reached'), ('game_perfect_score', 'Perfect Score In A Game'), ('combo', 'Combo Reached'), ('coins_earned', 'Total Coins Earned'), ('word_hunter_words_found', 'Total Words Found In Word Hunter'), ('memory_cards_completed', 'Memory Cards Sessions Completed')], max_length=30)),
                ('condition_value', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['condition_type', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True)),
                ('name', models.CharField(default='Player', max_length=100)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('weekly_xp', models.PositiveIntegerField(default=0)),
                ('week_reset_date', models.DateField(blank=True, null=True)),
                ('last_daily_claim_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-xp'],
            },
        ),
        migrations.CreateModel(
            name='VocabWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40, unique=True)),
                ('meaning', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('food', 'Food & Dining'), ('work', 'Work & Business'), ('daily', 'Daily Life'), ('health', 'Health'), ('nature', 'Nature & Weather')], default='daily', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
            ],
            options={
                'verbose_name': 'Vocabulary Word',
                'verbose_name_plural': 'Vocabulary Words',
                'ordering': ['category', 'difficulty', 'word'],
            },
        ),
        migrations.CreateModel(
            name='GamePlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('verbquest', 'VerbQuest'), ('word_hunter', 'Word Hunter'), ('memory_cards', 'Memory Cards')], max_length=30)),
                ('score', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('coins_earned', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to='gamification.player')),
            ],
            options={
                'verbose_name': 'Game Play Session',
                'verbose_name_plural': 'Game Play Sessions',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='gamification.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_achievements', to='gamification.player')),
            ],
            options={
                'verbose_name': 'Player Achievement',
                'verbose_name_plural': 'Player Achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
