# Generated by Django 5.2.15 on 2026-07-08 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_player_password_hash_player_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('icon', models.CharField(default='📘', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Grammar Topic',
                'verbose_name_plural': 'Grammar Topics',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('games_played', 'Total Games Played'), ('streak', 'Streak Days Reached'), ('total_xp', 'Total XP Reached'), ('game_perfect_score', 'Perfect Score In A Game'), ('combo', 'Combo Reached'), ('coins_earned', 'Total Coins Earned'), ('word_hunter_words_found', 'Total Words Found In Word Hunter'), ('memory_cards_completed', 'Memory Cards Sessions Completed'), ('grammar_topics_completed', 'Grammar Topics Completed'), ('boss_rounds_cleared', 'Grammar Boss Rounds Cleared')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gameplaysession',
            name='game_type',
            field=models.CharField(choices=[('verbquest', 'VerbQuest'), ('word_hunter', 'Word Hunter'), ('memory_cards', 'Memory Cards'), ('grammar_battle', 'Grammar Battle')], max_length=30),
        ),
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill In The Blank'), ('drag_drop', 'Drag And Drop (Word Order)')], max_length=20)),
                ('prompt', models.CharField(max_length=300)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(max_length=200)),
                ('is_boss', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gamification.grammartopic')),
            ],
            options={
                'verbose_name': 'Grammar Question',
                'verbose_name_plural': 'Grammar Questions',
                'ordering': ['topic', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('best_score_pct', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='gamification.player')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='gamification.grammartopic')),
            ],
            options={
                'verbose_name': 'Player Topic Progress',
                'verbose_name_plural': 'Player Topic Progress',
                'unique_together': {('player', 'topic')},
            },
        ),
    ]
