# Generated by Django 5.2.15 on 2026-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_grammartopic_alter_achievement_condition_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartopic',
            name='lesson_examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='lesson_rule',
            field=models.TextField(blank=True),
        ),
    ]
