# Generated by Django 5.2.15 on 2026-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_grammartopic_lesson_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartopic',
            name='lesson_common_mistakes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='lesson_signal_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='lesson_structure',
            field=models.TextField(blank=True),
        ),
    ]
