# Generated by Django 5.2.15 on 2026-07-08 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_grammartopic_lesson_common_mistakes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=50)),
                ('npc_line', models.CharField(max_length=300)),
                ('is_start', models.BooleanField(default=False)),
                ('is_ending', models.BooleanField(default=False)),
                ('ending_quality', models.CharField(blank=True, choices=[('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad')], max_length=10)),
            ],
            options={
                'verbose_name': 'Survival Node',
                'verbose_name_plural': 'Survival Nodes',
                'ordering': ['scenario', 'node_key'],
            },
        ),
        migrations.CreateModel(
            name='SurvivalScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🧳', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Survival Scenario',
                'verbose_name_plural': 'Survival Scenarios',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('games_played', 'Total Games Played'), ('streak', 'Streak Days Reached'), ('total_xp', 'Total XP Reached'), ('game_perfect_score', 'Perfect Score In A Game'), ('combo', 'Combo Reached'), ('coins_earned', 'Total Coins Earned'), ('word_hunter_words_found', 'Total Words Found In Word Hunter'), ('memory_cards_completed', 'Memory Cards Sessions Completed'), ('grammar_topics_completed', 'Grammar Topics Completed'), ('boss_rounds_cleared', 'Grammar Boss Rounds Cleared'), ('survival_scenarios_completed', 'Survival Scenarios Completed (Good Ending)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gameplaysession',
            name='game_type',
            field=models.CharField(choices=[('verbquest', 'VerbQuest'), ('word_hunter', 'Word Hunter'), ('memory_cards', 'Memory Cards'), ('grammar_battle', 'Grammar Battle'), ('survival_challenge', 'Daily Survival Challenge')], max_length=30),
        ),
        migrations.CreateModel(
            name='SurvivalChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('quality', models.CharField(choices=[('good', 'Good'), ('ok', 'OK'), ('bad', 'Bad')], max_length=10)),
                ('feedback', models.CharField(max_length=300)),
                ('next_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reached_by', to='gamification.survivalnode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='gamification.survivalnode')),
            ],
            options={
                'verbose_name': 'Survival Choice',
                'verbose_name_plural': 'Survival Choices',
                'ordering': ['node', 'id'],
            },
        ),
        migrations.AddField(
            model_name='survivalnode',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='gamification.survivalscenario'),
        ),
        migrations.AlterUniqueTogether(
            name='survivalnode',
            unique_together={('scenario', 'node_key')},
        ),
        migrations.CreateModel(
            name='PlayerSurvivalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('best_ending_quality', models.CharField(blank=True, max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survival_progress', to='gamification.player')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='gamification.survivalscenario')),
            ],
            options={
                'verbose_name': 'Player Survival Progress',
                'verbose_name_plural': 'Player Survival Progress',
                'unique_together': {('player', 'scenario')},
            },
        ),
    ]
