# Generated by Django 5.2.15 on 2026-07-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_survivalnode_survivalscenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VBPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Vocabulary Builder Passage',
                'verbose_name_plural': 'Vocabulary Builder Passages',
            },
        ),
        migrations.CreateModel(
            name='VBUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('icon', models.CharField(default='📖', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Vocabulary Builder Unit',
                'verbose_name_plural': 'Vocabulary Builder Units',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('games_played', 'Total Games Played'), ('streak', 'Streak Days Reached'), ('total_xp', 'Total XP Reached'), ('game_perfect_score', 'Perfect Score In A Game'), ('combo', 'Combo Reached'), ('coins_earned', 'Total Coins Earned'), ('word_hunter_words_found', 'Total Words Found In Word Hunter'), ('memory_cards_completed', 'Memory Cards Sessions Completed'), ('grammar_topics_completed', 'Grammar Topics Completed'), ('boss_rounds_cleared', 'Grammar Boss Rounds Cleared'), ('survival_scenarios_completed', 'Survival Scenarios Completed (Good Ending)'), ('vocab_units_completed', 'Vocabulary Builder Units Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='gameplaysession',
            name='game_type',
            field=models.CharField(choices=[('verbquest', 'VerbQuest'), ('word_hunter', 'Word Hunter'), ('memory_cards', 'Memory Cards'), ('grammar_battle', 'Grammar Battle'), ('survival_challenge', 'Daily Survival Challenge'), ('vocabulary_builder', 'Vocabulary Builder')], max_length=30),
        ),
        migrations.CreateModel(
            name='VBPassageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=300)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=200)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gamification.vbpassage')),
            ],
            options={
                'verbose_name': 'Vocabulary Builder Passage Question',
                'verbose_name_plural': 'Vocabulary Builder Passage Questions',
                'ordering': ['passage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VBQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice')], default='multiple_choice', max_length=20)),
                ('prompt', models.CharField(max_length=300)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=200)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gamification.vbunit')),
            ],
            options={
                'verbose_name': 'Vocabulary Builder Question',
                'verbose_name_plural': 'Vocabulary Builder Questions',
                'ordering': ['unit', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vbpassage',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passage', to='gamification.vbunit'),
        ),
        migrations.CreateModel(
            name='PlayerVBUnitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('best_score_pct', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vb_progress', to='gamification.player')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='gamification.vbunit')),
            ],
            options={
                'verbose_name': 'Player Vocabulary Unit Progress',
                'verbose_name_plural': 'Player Vocabulary Unit Progress',
                'unique_together': {('player', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='VBWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('pronunciation', models.CharField(blank=True, max_length=60)),
                ('part_of_speech', models.CharField(blank=True, max_length=12)),
                ('definition', models.CharField(max_length=300)),
                ('example_sentence', models.CharField(max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='gamification.vbunit')),
            ],
            options={
                'verbose_name': 'Vocabulary Builder Word',
                'verbose_name_plural': 'Vocabulary Builder Words',
                'ordering': ['unit', 'order'],
                'unique_together': {('unit', 'word')},
            },
        ),
    ]
